"""empty message

Revision ID: 0d79bd97dde8
Revises: de37b53f565f
Create Date: 2020-06-24 21:00:28.879514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d79bd97dde8'
down_revision = 'de37b53f565f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'user', ['role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
